apiVersion: v1
kind: Service
metadata: 
  name: roadrunner-ecommerce-store-service
  labels:
    app: roadrunner-ecommerce-store-service
spec:
  type: LoadBalancer
  selector:
    app: roadrunner-ecommerce-store-server
  ports:
    - port: 80

