apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    app: nginx-server
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: nginx-container
          image: nginx:stable-alpine3.17-slim
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /usr/share/nginx/html
      volumes:
        - name: code
          hostPath:
            path: /home/docker/code