apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432