apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: mysqldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi #5 GB
      